---
- name: Restart Graylog Data Node
  ansible.builtin.systemd_service:
    name: "{{ graylog_datanode_service_name }}"
    state: restarted
  when: soc_iac_restart_confirmed | bool
  listen: Restart Graylog Data Node
