---
all:
  vars:
    ansible_user: automation
  children:
    graylog_core:
      hosts:
        graylog-core-1: {ansible_host: 192.0.2.20, graylog_is_leader: true}
        graylog-core-2: {ansible_host: 192.0.2.21, graylog_is_leader: false}
        graylog-core-3: {ansible_host: 192.0.2.22, graylog_is_leader: false}
    graylog_datanode:
      hosts:
        graylog-data-1: {ansible_host: 192.0.2.23}
        graylog-data-2: {ansible_host: 192.0.2.24}
        graylog-data-3: {ansible_host: 192.0.2.25}
    wazuh_manager:
      hosts:
        wazuh-manager-1: {ansible_host: 192.0.2.26, wazuh_manager_type: master}
        wazuh-manager-2: {ansible_host: 192.0.2.27, wazuh_manager_type: worker}
        wazuh-manager-3: {ansible_host: 192.0.2.28, wazuh_manager_type: worker}
    wazuh_indexer:
      hosts:
        wazuh-indexer-1: {ansible_host: 192.0.2.29}
        wazuh-indexer-2: {ansible_host: 192.0.2.30}
        wazuh-indexer-3: {ansible_host: 192.0.2.31}
    wazuh_dashboard:
      hosts:
        wazuh-dashboard-1: {ansible_host: 192.0.2.32}
        wazuh-dashboard-2: {ansible_host: 192.0.2.33}
    siem_edge:
      hosts:
        siem-edge-2: {ansible_host: 192.0.2.35, keepalived_priority: 140, keepalived_peer: 192.0.2.34}
        siem-edge-1: {ansible_host: 192.0.2.34, keepalived_priority: 150, keepalived_peer: 192.0.2.35}
    soc_collectors:
      hosts:
        soc-collector-1: {ansible_host: 192.0.2.40}
    shuffle:
      hosts:
        soar-1: {ansible_host: 192.0.2.41}
    wazuh_agent_targets:
      hosts: {}
