---
wazuh_manager_config_path: /var/ossec/etc/ossec.conf
wazuh_manager_package_name: wazuh-manager
wazuh_manager_package_version: ""
wazuh_manager_install_package: true
wazuh_manager_update_cache: false
wazuh_manager_service_name: wazuh-manager
wazuh_manager_artifact_root: "{{ playbook_dir }}/../artifacts"
wazuh_manager_artifacts: []
wazuh_manager_validation_command:
  - /usr/bin/python3
  - -c
  - "import sys, xml.etree.ElementTree as ET; ET.parse(sys.argv[1])"
