---
wazuh_manager_config_path: /var/ossec/etc/ossec.conf
wazuh_manager_artifacts:
  - {src: wazuh/rules/dns_rules.xml, dest: /var/ossec/etc/rules/dns_rules.xml}
  - {src: wazuh/rules/greenbone_rules.xml, dest: /var/ossec/etc/rules/greenbone_rules.xml}
  - {src: wazuh/rules/hashicorp_vault_rules.xml, dest: /var/ossec/etc/rules/hashicorp_vault_rules.xml}
  - {src: wazuh/rules/unifi_efg_contract_rules.xml, dest: /var/ossec/etc/rules/unifi_efg_contract_rules.xml}
  - {src: wazuh/rules/unifi_protect_rules.xml, dest: /var/ossec/etc/rules/unifi_protect_rules.xml}
  - {src: wazuh/rules/vaultwarden_rules.xml, dest: /var/ossec/etc/rules/vaultwarden_rules.xml}
  - {src: wazuh/waf_rules.xml, dest: /var/ossec/etc/rules/waf_rules.xml}
  - {src: wazuh/decoders/greenbone_decoders.xml, dest: /var/ossec/etc/decoders/greenbone_decoders.xml}
