---
- name: Restart Wazuh manager
  ansible.builtin.systemd_service:
    name: "{{ wazuh_manager_service_name }}"
    state: restarted
  when: soc_iac_restart_confirmed | bool
  listen: Restart Wazuh manager
